// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/packetyeeter.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalType int32

const (
	SignalType_SIGNAL_UNKNOWN SignalType = 0
	// eBPF signals
	SignalType_SIGNAL_SYN_FLOOD            SignalType = 1
	SignalType_SIGNAL_BAD_FLAGS            SignalType = 2
	SignalType_SIGNAL_ICMP_FLOOD           SignalType = 3
	SignalType_SIGNAL_UDP_FLOOD            SignalType = 4
	SignalType_SIGNAL_TTL_ANOMALY          SignalType = 5
	SignalType_SIGNAL_WINDOW_ANOMALY       SignalType = 6
	SignalType_SIGNAL_PACKET_SIZE_UNIFORM  SignalType = 7
	SignalType_SIGNAL_TIMING_PATTERN       SignalType = 8
	SignalType_SIGNAL_PORT_SCANNING        SignalType = 9
	SignalType_SIGNAL_INCOMPLETE_HANDSHAKE SignalType = 10
	SignalType_SIGNAL_TCP_METADATA         SignalType = 11 // Per-packet TCP metadata (timestamps, entropy)
	// Fingerprint signals
	SignalType_SIGNAL_JA4T_SUSPICIOUS        SignalType = 40
	SignalType_SIGNAL_HIGH_LATENCY_HANDSHAKE SignalType = 41
	SignalType_SIGNAL_LATENCY_MISMATCH       SignalType = 42
	SignalType_SIGNAL_GEO_ANOMALY            SignalType = 43
	SignalType_SIGNAL_CONNECTION_PATTERN     SignalType = 44
	// Analysis signals
	SignalType_SIGNAL_CLOCK_SKEW_ANOMALY SignalType = 50
	SignalType_SIGNAL_ENTROPY_ANOMALY    SignalType = 51
	SignalType_SIGNAL_BASELINE_ANOMALY   SignalType = 52
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0:  "SIGNAL_UNKNOWN",
		1:  "SIGNAL_SYN_FLOOD",
		2:  "SIGNAL_BAD_FLAGS",
		3:  "SIGNAL_ICMP_FLOOD",
		4:  "SIGNAL_UDP_FLOOD",
		5:  "SIGNAL_TTL_ANOMALY",
		6:  "SIGNAL_WINDOW_ANOMALY",
		7:  "SIGNAL_PACKET_SIZE_UNIFORM",
		8:  "SIGNAL_TIMING_PATTERN",
		9:  "SIGNAL_PORT_SCANNING",
		10: "SIGNAL_INCOMPLETE_HANDSHAKE",
		11: "SIGNAL_TCP_METADATA",
		40: "SIGNAL_JA4T_SUSPICIOUS",
		41: "SIGNAL_HIGH_LATENCY_HANDSHAKE",
		42: "SIGNAL_LATENCY_MISMATCH",
		43: "SIGNAL_GEO_ANOMALY",
		44: "SIGNAL_CONNECTION_PATTERN",
		50: "SIGNAL_CLOCK_SKEW_ANOMALY",
		51: "SIGNAL_ENTROPY_ANOMALY",
		52: "SIGNAL_BASELINE_ANOMALY",
	}
	SignalType_value = map[string]int32{
		"SIGNAL_UNKNOWN":                0,
		"SIGNAL_SYN_FLOOD":              1,
		"SIGNAL_BAD_FLAGS":              2,
		"SIGNAL_ICMP_FLOOD":             3,
		"SIGNAL_UDP_FLOOD":              4,
		"SIGNAL_TTL_ANOMALY":            5,
		"SIGNAL_WINDOW_ANOMALY":         6,
		"SIGNAL_PACKET_SIZE_UNIFORM":    7,
		"SIGNAL_TIMING_PATTERN":         8,
		"SIGNAL_PORT_SCANNING":          9,
		"SIGNAL_INCOMPLETE_HANDSHAKE":   10,
		"SIGNAL_TCP_METADATA":           11,
		"SIGNAL_JA4T_SUSPICIOUS":        40,
		"SIGNAL_HIGH_LATENCY_HANDSHAKE": 41,
		"SIGNAL_LATENCY_MISMATCH":       42,
		"SIGNAL_GEO_ANOMALY":            43,
		"SIGNAL_CONNECTION_PATTERN":     44,
		"SIGNAL_CLOCK_SKEW_ANOMALY":     50,
		"SIGNAL_ENTROPY_ANOMALY":        51,
		"SIGNAL_BASELINE_ANOMALY":       52,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_packetyeeter_proto_enumTypes[0].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_v1_packetyeeter_proto_enumTypes[0]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{0}
}

type SignalSource int32

const (
	SignalSource_SOURCE_UNKNOWN       SignalSource = 0
	SignalSource_SOURCE_EBPF          SignalSource = 1
	SignalSource_SOURCE_FINGERPRINTER SignalSource = 3
	SignalSource_SOURCE_HAPROXY       SignalSource = 4
	SignalSource_SOURCE_ANALYZER      SignalSource = 5
)

// Enum value maps for SignalSource.
var (
	SignalSource_name = map[int32]string{
		0: "SOURCE_UNKNOWN",
		1: "SOURCE_EBPF",
		3: "SOURCE_FINGERPRINTER",
		4: "SOURCE_HAPROXY",
		5: "SOURCE_ANALYZER",
	}
	SignalSource_value = map[string]int32{
		"SOURCE_UNKNOWN":       0,
		"SOURCE_EBPF":          1,
		"SOURCE_FINGERPRINTER": 3,
		"SOURCE_HAPROXY":       4,
		"SOURCE_ANALYZER":      5,
	}
)

func (x SignalSource) Enum() *SignalSource {
	p := new(SignalSource)
	*p = x
	return p
}

func (x SignalSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalSource) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_packetyeeter_proto_enumTypes[1].Descriptor()
}

func (SignalSource) Type() protoreflect.EnumType {
	return &file_v1_packetyeeter_proto_enumTypes[1]
}

func (x SignalSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalSource.Descriptor instead.
func (SignalSource) EnumDescriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{1}
}

type CommandType int32

const (
	CommandType_COMMAND_UNKNOWN             CommandType = 0
	CommandType_COMMAND_BLOCK_IP            CommandType = 1
	CommandType_COMMAND_UNBLOCK_IP          CommandType = 2
	CommandType_COMMAND_BLOCK_CIDR          CommandType = 3
	CommandType_COMMAND_UNBLOCK_CIDR        CommandType = 4
	CommandType_COMMAND_ALLOWLIST_IP        CommandType = 5
	CommandType_COMMAND_REMOVE_ALLOWLIST_IP CommandType = 6
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_UNKNOWN",
		1: "COMMAND_BLOCK_IP",
		2: "COMMAND_UNBLOCK_IP",
		3: "COMMAND_BLOCK_CIDR",
		4: "COMMAND_UNBLOCK_CIDR",
		5: "COMMAND_ALLOWLIST_IP",
		6: "COMMAND_REMOVE_ALLOWLIST_IP",
	}
	CommandType_value = map[string]int32{
		"COMMAND_UNKNOWN":             0,
		"COMMAND_BLOCK_IP":            1,
		"COMMAND_UNBLOCK_IP":          2,
		"COMMAND_BLOCK_CIDR":          3,
		"COMMAND_UNBLOCK_CIDR":        4,
		"COMMAND_ALLOWLIST_IP":        5,
		"COMMAND_REMOVE_ALLOWLIST_IP": 6,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_packetyeeter_proto_enumTypes[2].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_v1_packetyeeter_proto_enumTypes[2]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{2}
}

type BotCategory int32

const (
	BotCategory_BOT_CATEGORY_UNKNOWN       BotCategory = 0
	BotCategory_BOT_CATEGORY_SEARCH_ENGINE BotCategory = 1
	BotCategory_BOT_CATEGORY_SOCIAL_MEDIA  BotCategory = 2
	BotCategory_BOT_CATEGORY_LEGITIMATE    BotCategory = 3
	BotCategory_BOT_CATEGORY_AI_CRAWLER    BotCategory = 4
	BotCategory_BOT_CATEGORY_SCRAPER       BotCategory = 5
	BotCategory_BOT_CATEGORY_MALICIOUS     BotCategory = 6
)

// Enum value maps for BotCategory.
var (
	BotCategory_name = map[int32]string{
		0: "BOT_CATEGORY_UNKNOWN",
		1: "BOT_CATEGORY_SEARCH_ENGINE",
		2: "BOT_CATEGORY_SOCIAL_MEDIA",
		3: "BOT_CATEGORY_LEGITIMATE",
		4: "BOT_CATEGORY_AI_CRAWLER",
		5: "BOT_CATEGORY_SCRAPER",
		6: "BOT_CATEGORY_MALICIOUS",
	}
	BotCategory_value = map[string]int32{
		"BOT_CATEGORY_UNKNOWN":       0,
		"BOT_CATEGORY_SEARCH_ENGINE": 1,
		"BOT_CATEGORY_SOCIAL_MEDIA":  2,
		"BOT_CATEGORY_LEGITIMATE":    3,
		"BOT_CATEGORY_AI_CRAWLER":    4,
		"BOT_CATEGORY_SCRAPER":       5,
		"BOT_CATEGORY_MALICIOUS":     6,
	}
)

func (x BotCategory) Enum() *BotCategory {
	p := new(BotCategory)
	*p = x
	return p
}

func (x BotCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BotCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_packetyeeter_proto_enumTypes[3].Descriptor()
}

func (BotCategory) Type() protoreflect.EnumType {
	return &file_v1_packetyeeter_proto_enumTypes[3]
}

func (x BotCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BotCategory.Descriptor instead.
func (BotCategory) EnumDescriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{3}
}

type EntityType int32

const (
	EntityType_ENTITY_UNKNOWN EntityType = 0
	EntityType_ENTITY_IP      EntityType = 1
	EntityType_ENTITY_ASN     EntityType = 2
	EntityType_ENTITY_JA4H    EntityType = 3
	EntityType_ENTITY_JA4T    EntityType = 4
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_UNKNOWN",
		1: "ENTITY_IP",
		2: "ENTITY_ASN",
		3: "ENTITY_JA4H",
		4: "ENTITY_JA4T",
	}
	EntityType_value = map[string]int32{
		"ENTITY_UNKNOWN": 0,
		"ENTITY_IP":      1,
		"ENTITY_ASN":     2,
		"ENTITY_JA4H":    3,
		"ENTITY_JA4T":    4,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_packetyeeter_proto_enumTypes[4].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_v1_packetyeeter_proto_enumTypes[4]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{4}
}

// Signal represents a detection signal from the collector
type Signal struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type      SignalType             `protobuf:"varint,3,opt,name=type,proto3,enum=packetyeeter.v1.SignalType" json:"type,omitempty"`
	Source    SignalSource           `protobuf:"varint,4,opt,name=source,proto3,enum=packetyeeter.v1.SignalSource" json:"source,omitempty"`
	// Network context
	Ip  []byte `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"` // Can be IPv4 or IPv6
	Asn string `protobuf:"bytes,6,opt,name=asn,proto3" json:"asn,omitempty"`
	Org string `protobuf:"bytes,7,opt,name=org,proto3" json:"org,omitempty"`
	// Fingerprints
	Ja4H string `protobuf:"bytes,8,opt,name=ja4h,proto3" json:"ja4h,omitempty"`
	Ja4T string `protobuf:"bytes,9,opt,name=ja4t,proto3" json:"ja4t,omitempty"`
	Ja4S string `protobuf:"bytes,10,opt,name=ja4s,proto3" json:"ja4s,omitempty"`
	// Weight for scoring
	Weight float64 `protobuf:"fixed64,11,opt,name=weight,proto3" json:"weight,omitempty"`
	// Additional metadata
	Metadata map[string]string `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// TCP context (from eBPF)
	TcpContext *TCPContext `protobuf:"bytes,14,opt,name=tcp_context,json=tcpContext,proto3" json:"tcp_context,omitempty"`
	// TLS JA4 (client hello)
	Ja4           string `protobuf:"bytes,15,opt,name=ja4,proto3" json:"ja4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_v1_packetyeeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{0}
}

func (x *Signal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Signal) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Signal) GetType() SignalType {
	if x != nil {
		return x.Type
	}
	return SignalType_SIGNAL_UNKNOWN
}

func (x *Signal) GetSource() SignalSource {
	if x != nil {
		return x.Source
	}
	return SignalSource_SOURCE_UNKNOWN
}

func (x *Signal) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *Signal) GetAsn() string {
	if x != nil {
		return x.Asn
	}
	return ""
}

func (x *Signal) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *Signal) GetJa4H() string {
	if x != nil {
		return x.Ja4H
	}
	return ""
}

func (x *Signal) GetJa4T() string {
	if x != nil {
		return x.Ja4T
	}
	return ""
}

func (x *Signal) GetJa4S() string {
	if x != nil {
		return x.Ja4S
	}
	return ""
}

func (x *Signal) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Signal) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Signal) GetTcpContext() *TCPContext {
	if x != nil {
		return x.TcpContext
	}
	return nil
}

func (x *Signal) GetJa4() string {
	if x != nil {
		return x.Ja4
	}
	return ""
}

type TCPContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SynCount       uint32                 `protobuf:"varint,1,opt,name=syn_count,json=synCount,proto3" json:"syn_count,omitempty"`
	RstCount       uint32                 `protobuf:"varint,2,opt,name=rst_count,json=rstCount,proto3" json:"rst_count,omitempty"`
	FinCount       uint32                 `protobuf:"varint,3,opt,name=fin_count,json=finCount,proto3" json:"fin_count,omitempty"`
	Ttl            uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	WindowSize     uint32                 `protobuf:"varint,5,opt,name=window_size,json=windowSize,proto3" json:"window_size,omitempty"`
	Mss            uint32                 `protobuf:"varint,6,opt,name=mss,proto3" json:"mss,omitempty"`
	TcpOptions     uint32                 `protobuf:"varint,7,opt,name=tcp_options,json=tcpOptions,proto3" json:"tcp_options,omitempty"`
	HandshakeRttNs int64                  `protobuf:"varint,8,opt,name=handshake_rtt_ns,json=handshakeRttNs,proto3" json:"handshake_rtt_ns,omitempty"`
	TcpTimestamp   uint32                 `protobuf:"varint,9,opt,name=tcp_timestamp,json=tcpTimestamp,proto3" json:"tcp_timestamp,omitempty"`  // TCP timestamp value (TSval) for clock skew analysis
	EntropyScore   uint32                 `protobuf:"varint,10,opt,name=entropy_score,json=entropyScore,proto3" json:"entropy_score,omitempty"` // Payload entropy estimate (0-100)
	TcpFlags       uint32                 `protobuf:"varint,11,opt,name=tcp_flags,json=tcpFlags,proto3" json:"tcp_flags,omitempty"`             // Raw TCP flags byte (SYN=0x02, ACK=0x10, etc.)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TCPContext) Reset() {
	*x = TCPContext{}
	mi := &file_v1_packetyeeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPContext) ProtoMessage() {}

func (x *TCPContext) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPContext.ProtoReflect.Descriptor instead.
func (*TCPContext) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{1}
}

func (x *TCPContext) GetSynCount() uint32 {
	if x != nil {
		return x.SynCount
	}
	return 0
}

func (x *TCPContext) GetRstCount() uint32 {
	if x != nil {
		return x.RstCount
	}
	return 0
}

func (x *TCPContext) GetFinCount() uint32 {
	if x != nil {
		return x.FinCount
	}
	return 0
}

func (x *TCPContext) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *TCPContext) GetWindowSize() uint32 {
	if x != nil {
		return x.WindowSize
	}
	return 0
}

func (x *TCPContext) GetMss() uint32 {
	if x != nil {
		return x.Mss
	}
	return 0
}

func (x *TCPContext) GetTcpOptions() uint32 {
	if x != nil {
		return x.TcpOptions
	}
	return 0
}

func (x *TCPContext) GetHandshakeRttNs() int64 {
	if x != nil {
		return x.HandshakeRttNs
	}
	return 0
}

func (x *TCPContext) GetTcpTimestamp() uint32 {
	if x != nil {
		return x.TcpTimestamp
	}
	return 0
}

func (x *TCPContext) GetEntropyScore() uint32 {
	if x != nil {
		return x.EntropyScore
	}
	return 0
}

func (x *TCPContext) GetTcpFlags() uint32 {
	if x != nil {
		return x.TcpFlags
	}
	return 0
}

// Command represents an action for the collector to execute
type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type      CommandType            `protobuf:"varint,3,opt,name=type,proto3,enum=packetyeeter.v1.CommandType" json:"type,omitempty"`
	// Target
	Ip   []byte `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Cidr string `protobuf:"bytes,5,opt,name=cidr,proto3" json:"cidr,omitempty"` // For network-level blocks
	// Duration (for temporary blocks)
	DurationSeconds int64 `protobuf:"varint,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	// Reason for audit trail
	Reason string `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	// Priority (higher = more urgent)
	Priority int32 `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	// Source that triggered this command
	Source        string `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_v1_packetyeeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_UNKNOWN
}

func (x *Command) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *Command) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *Command) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Command) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Command) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Command) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// JA4H Lookup
type JA4HLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JA4HLookupRequest) Reset() {
	*x = JA4HLookupRequest{}
	mi := &file_v1_packetyeeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JA4HLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JA4HLookupRequest) ProtoMessage() {}

func (x *JA4HLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JA4HLookupRequest.ProtoReflect.Descriptor instead.
func (*JA4HLookupRequest) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{3}
}

func (x *JA4HLookupRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type JA4HLookupResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Found           bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Application     string                 `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	Library         string                 `protobuf:"bytes,3,opt,name=library,proto3" json:"library,omitempty"`
	Device          string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Verified        bool                   `protobuf:"varint,5,opt,name=verified,proto3" json:"verified,omitempty"`
	Category        string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"` // "browser", "bot", "scanner", "malware", etc.
	ThreatScore     float64                `protobuf:"fixed64,7,opt,name=threat_score,json=threatScore,proto3" json:"threat_score,omitempty"`
	IsWildcardMatch bool                   `protobuf:"varint,8,opt,name=is_wildcard_match,json=isWildcardMatch,proto3" json:"is_wildcard_match,omitempty"` // True if matched via partial/wildcard
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JA4HLookupResponse) Reset() {
	*x = JA4HLookupResponse{}
	mi := &file_v1_packetyeeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JA4HLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JA4HLookupResponse) ProtoMessage() {}

func (x *JA4HLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JA4HLookupResponse.ProtoReflect.Descriptor instead.
func (*JA4HLookupResponse) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{4}
}

func (x *JA4HLookupResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *JA4HLookupResponse) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *JA4HLookupResponse) GetLibrary() string {
	if x != nil {
		return x.Library
	}
	return ""
}

func (x *JA4HLookupResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *JA4HLookupResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *JA4HLookupResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *JA4HLookupResponse) GetThreatScore() float64 {
	if x != nil {
		return x.ThreatScore
	}
	return 0
}

func (x *JA4HLookupResponse) GetIsWildcardMatch() bool {
	if x != nil {
		return x.IsWildcardMatch
	}
	return false
}

// JA4T Lookup
type JA4TLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"` // For correlation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JA4TLookupRequest) Reset() {
	*x = JA4TLookupRequest{}
	mi := &file_v1_packetyeeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JA4TLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JA4TLookupRequest) ProtoMessage() {}

func (x *JA4TLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JA4TLookupRequest.ProtoReflect.Descriptor instead.
func (*JA4TLookupRequest) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{5}
}

func (x *JA4TLookupRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *JA4TLookupRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type JA4TLookupResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Suspicious      bool                   `protobuf:"varint,1,opt,name=suspicious,proto3" json:"suspicious,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RiskScore       float64                `protobuf:"fixed64,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	MatchedPatterns []string               `protobuf:"bytes,4,rep,name=matched_patterns,json=matchedPatterns,proto3" json:"matched_patterns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JA4TLookupResponse) Reset() {
	*x = JA4TLookupResponse{}
	mi := &file_v1_packetyeeter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JA4TLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JA4TLookupResponse) ProtoMessage() {}

func (x *JA4TLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JA4TLookupResponse.ProtoReflect.Descriptor instead.
func (*JA4TLookupResponse) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{6}
}

func (x *JA4TLookupResponse) GetSuspicious() bool {
	if x != nil {
		return x.Suspicious
	}
	return false
}

func (x *JA4TLookupResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *JA4TLookupResponse) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *JA4TLookupResponse) GetMatchedPatterns() []string {
	if x != nil {
		return x.MatchedPatterns
	}
	return nil
}

// Bot Verification
type BotVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ForceLookup   bool                   `protobuf:"varint,3,opt,name=force_lookup,json=forceLookup,proto3" json:"force_lookup,omitempty"` // Bypass cache
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotVerifyRequest) Reset() {
	*x = BotVerifyRequest{}
	mi := &file_v1_packetyeeter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotVerifyRequest) ProtoMessage() {}

func (x *BotVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotVerifyRequest.ProtoReflect.Descriptor instead.
func (*BotVerifyRequest) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{7}
}

func (x *BotVerifyRequest) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *BotVerifyRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *BotVerifyRequest) GetForceLookup() bool {
	if x != nil {
		return x.ForceLookup
	}
	return false
}

type BotVerifyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsVerified      bool                   `protobuf:"varint,1,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	BotType         string                 `protobuf:"bytes,2,opt,name=bot_type,json=botType,proto3" json:"bot_type,omitempty"` // "googlebot", "bingbot", etc.
	ReverseDns      string                 `protobuf:"bytes,3,opt,name=reverse_dns,json=reverseDns,proto3" json:"reverse_dns,omitempty"`
	ForwardDns      string                 `protobuf:"bytes,4,opt,name=forward_dns,json=forwardDns,proto3" json:"forward_dns,omitempty"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	IsImpersonation bool                   `protobuf:"varint,6,opt,name=is_impersonation,json=isImpersonation,proto3" json:"is_impersonation,omitempty"`
	Category        BotCategory            `protobuf:"varint,7,opt,name=category,proto3,enum=packetyeeter.v1.BotCategory" json:"category,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BotVerifyResponse) Reset() {
	*x = BotVerifyResponse{}
	mi := &file_v1_packetyeeter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotVerifyResponse) ProtoMessage() {}

func (x *BotVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotVerifyResponse.ProtoReflect.Descriptor instead.
func (*BotVerifyResponse) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{8}
}

func (x *BotVerifyResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *BotVerifyResponse) GetBotType() string {
	if x != nil {
		return x.BotType
	}
	return ""
}

func (x *BotVerifyResponse) GetReverseDns() string {
	if x != nil {
		return x.ReverseDns
	}
	return ""
}

func (x *BotVerifyResponse) GetForwardDns() string {
	if x != nil {
		return x.ForwardDns
	}
	return ""
}

func (x *BotVerifyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BotVerifyResponse) GetIsImpersonation() bool {
	if x != nil {
		return x.IsImpersonation
	}
	return false
}

func (x *BotVerifyResponse) GetCategory() BotCategory {
	if x != nil {
		return x.Category
	}
	return BotCategory_BOT_CATEGORY_UNKNOWN
}

// AI Crawler Verification
type AICrawlerVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AICrawlerVerifyRequest) Reset() {
	*x = AICrawlerVerifyRequest{}
	mi := &file_v1_packetyeeter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AICrawlerVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AICrawlerVerifyRequest) ProtoMessage() {}

func (x *AICrawlerVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AICrawlerVerifyRequest.ProtoReflect.Descriptor instead.
func (*AICrawlerVerifyRequest) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{9}
}

func (x *AICrawlerVerifyRequest) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *AICrawlerVerifyRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type AICrawlerVerifyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsVerified      bool                   `protobuf:"varint,1,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	CrawlerType     string                 `protobuf:"bytes,2,opt,name=crawler_type,json=crawlerType,proto3" json:"crawler_type,omitempty"` // "openai", "anthropic", "amazon", etc.
	IsImpersonation bool                   `protobuf:"varint,3,opt,name=is_impersonation,json=isImpersonation,proto3" json:"is_impersonation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AICrawlerVerifyResponse) Reset() {
	*x = AICrawlerVerifyResponse{}
	mi := &file_v1_packetyeeter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AICrawlerVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AICrawlerVerifyResponse) ProtoMessage() {}

func (x *AICrawlerVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AICrawlerVerifyResponse.ProtoReflect.Descriptor instead.
func (*AICrawlerVerifyResponse) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{10}
}

func (x *AICrawlerVerifyResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *AICrawlerVerifyResponse) GetCrawlerType() string {
	if x != nil {
		return x.CrawlerType
	}
	return ""
}

func (x *AICrawlerVerifyResponse) GetIsImpersonation() bool {
	if x != nil {
		return x.IsImpersonation
	}
	return false
}

// Threat Intelligence
type ThreatIntelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Enrich        bool                   `protobuf:"varint,2,opt,name=enrich,proto3" json:"enrich,omitempty"` // Trigger async enrichment if not cached
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatIntelRequest) Reset() {
	*x = ThreatIntelRequest{}
	mi := &file_v1_packetyeeter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatIntelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatIntelRequest) ProtoMessage() {}

func (x *ThreatIntelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatIntelRequest.ProtoReflect.Descriptor instead.
func (*ThreatIntelRequest) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{11}
}

func (x *ThreatIntelRequest) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *ThreatIntelRequest) GetEnrich() bool {
	if x != nil {
		return x.Enrich
	}
	return false
}

type ThreatIntelResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Found          bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	ThreatScore    float64                `protobuf:"fixed64,2,opt,name=threat_score,json=threatScore,proto3" json:"threat_score,omitempty"`
	IsKnownScanner bool                   `protobuf:"varint,3,opt,name=is_known_scanner,json=isKnownScanner,proto3" json:"is_known_scanner,omitempty"`
	IsTor          bool                   `protobuf:"varint,4,opt,name=is_tor,json=isTor,proto3" json:"is_tor,omitempty"`
	IsVpn          bool                   `protobuf:"varint,5,opt,name=is_vpn,json=isVpn,proto3" json:"is_vpn,omitempty"`
	IsCloud        bool                   `protobuf:"varint,6,opt,name=is_cloud,json=isCloud,proto3" json:"is_cloud,omitempty"`
	IsProxy        bool                   `protobuf:"varint,7,opt,name=is_proxy,json=isProxy,proto3" json:"is_proxy,omitempty"`
	Tags           []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Sources        []string               `protobuf:"bytes,9,rep,name=sources,proto3" json:"sources,omitempty"`
	OpenPorts      int32                  `protobuf:"varint,10,opt,name=open_ports,json=openPorts,proto3" json:"open_ports,omitempty"` // Count of open ports
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThreatIntelResponse) Reset() {
	*x = ThreatIntelResponse{}
	mi := &file_v1_packetyeeter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatIntelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatIntelResponse) ProtoMessage() {}

func (x *ThreatIntelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatIntelResponse.ProtoReflect.Descriptor instead.
func (*ThreatIntelResponse) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{12}
}

func (x *ThreatIntelResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ThreatIntelResponse) GetThreatScore() float64 {
	if x != nil {
		return x.ThreatScore
	}
	return 0
}

func (x *ThreatIntelResponse) GetIsKnownScanner() bool {
	if x != nil {
		return x.IsKnownScanner
	}
	return false
}

func (x *ThreatIntelResponse) GetIsTor() bool {
	if x != nil {
		return x.IsTor
	}
	return false
}

func (x *ThreatIntelResponse) GetIsVpn() bool {
	if x != nil {
		return x.IsVpn
	}
	return false
}

func (x *ThreatIntelResponse) GetIsCloud() bool {
	if x != nil {
		return x.IsCloud
	}
	return false
}

func (x *ThreatIntelResponse) GetIsProxy() bool {
	if x != nil {
		return x.IsProxy
	}
	return false
}

func (x *ThreatIntelResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ThreatIntelResponse) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ThreatIntelResponse) GetOpenPorts() int32 {
	if x != nil {
		return x.OpenPorts
	}
	return 0
}

// Reputation
type ReputationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "ip", "asn", "ja4h", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReputationRequest) Reset() {
	*x = ReputationRequest{}
	mi := &file_v1_packetyeeter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReputationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReputationRequest) ProtoMessage() {}

func (x *ReputationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReputationRequest.ProtoReflect.Descriptor instead.
func (*ReputationRequest) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{13}
}

func (x *ReputationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReputationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ReputationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	Offenses      int32                  `protobuf:"varint,2,opt,name=offenses,proto3" json:"offenses,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	IsBad         bool                   `protobuf:"varint,4,opt,name=is_bad,json=isBad,proto3" json:"is_bad,omitempty"` // Score exceeds threshold
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReputationResponse) Reset() {
	*x = ReputationResponse{}
	mi := &file_v1_packetyeeter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReputationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReputationResponse) ProtoMessage() {}

func (x *ReputationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReputationResponse.ProtoReflect.Descriptor instead.
func (*ReputationResponse) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{14}
}

func (x *ReputationResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ReputationResponse) GetOffenses() int32 {
	if x != nil {
		return x.Offenses
	}
	return 0
}

func (x *ReputationResponse) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *ReputationResponse) GetIsBad() bool {
	if x != nil {
		return x.IsBad
	}
	return false
}

func (x *ReputationResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Block Report
type BlockReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ip              []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Source          string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockReport) Reset() {
	*x = BlockReport{}
	mi := &file_v1_packetyeeter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReport) ProtoMessage() {}

func (x *BlockReport) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReport.ProtoReflect.Descriptor instead.
func (*BlockReport) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{15}
}

func (x *BlockReport) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *BlockReport) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BlockReport) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BlockReport) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *BlockReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Health
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSince   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=uptime_since,json=uptimeSince,proto3" json:"uptime_since,omitempty"`
	Components    map[string]string      `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Component name -> status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_v1_packetyeeter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_packetyeeter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_v1_packetyeeter_proto_rawDescGZIP(), []int{16}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSince() *timestamppb.Timestamp {
	if x != nil {
		return x.UptimeSince
	}
	return nil
}

func (x *HealthResponse) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

var File_v1_packetyeeter_proto protoreflect.FileDescriptor

const file_v1_packetyeeter_proto_rawDesc = "" +
	"\n" +
	"\x15v1/packetyeeter.proto\x12\x0fpacketyeeter.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x92\x04\n" +
	"\x06Signal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12/\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1b.packetyeeter.v1.SignalTypeR\x04type\x125\n" +
	"\x06source\x18\x04 \x01(\x0e2\x1d.packetyeeter.v1.SignalSourceR\x06source\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\fR\x02ip\x12\x10\n" +
	"\x03asn\x18\x06 \x01(\tR\x03asn\x12\x10\n" +
	"\x03org\x18\a \x01(\tR\x03org\x12\x12\n" +
	"\x04ja4h\x18\b \x01(\tR\x04ja4h\x12\x12\n" +
	"\x04ja4t\x18\t \x01(\tR\x04ja4t\x12\x12\n" +
	"\x04ja4s\x18\n" +
	" \x01(\tR\x04ja4s\x12\x16\n" +
	"\x06weight\x18\v \x01(\x01R\x06weight\x12A\n" +
	"\bmetadata\x18\f \x03(\v2%.packetyeeter.v1.Signal.MetadataEntryR\bmetadata\x12<\n" +
	"\vtcp_context\x18\x0e \x01(\v2\x1b.packetyeeter.v1.TCPContextR\n" +
	"tcpContext\x12\x10\n" +
	"\x03ja4\x18\x0f \x01(\tR\x03ja4\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x02\n" +
	"\n" +
	"TCPContext\x12\x1b\n" +
	"\tsyn_count\x18\x01 \x01(\rR\bsynCount\x12\x1b\n" +
	"\trst_count\x18\x02 \x01(\rR\brstCount\x12\x1b\n" +
	"\tfin_count\x18\x03 \x01(\rR\bfinCount\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12\x1f\n" +
	"\vwindow_size\x18\x05 \x01(\rR\n" +
	"windowSize\x12\x10\n" +
	"\x03mss\x18\x06 \x01(\rR\x03mss\x12\x1f\n" +
	"\vtcp_options\x18\a \x01(\rR\n" +
	"tcpOptions\x12(\n" +
	"\x10handshake_rtt_ns\x18\b \x01(\x03R\x0ehandshakeRttNs\x12#\n" +
	"\rtcp_timestamp\x18\t \x01(\rR\ftcpTimestamp\x12#\n" +
	"\rentropy_score\x18\n" +
	" \x01(\rR\fentropyScore\x12\x1b\n" +
	"\ttcp_flags\x18\v \x01(\rR\btcpFlags\"\xa0\x02\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x120\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1c.packetyeeter.v1.CommandTypeR\x04type\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\fR\x02ip\x12\x12\n" +
	"\x04cidr\x18\x05 \x01(\tR\x04cidr\x12)\n" +
	"\x10duration_seconds\x18\x06 \x01(\x03R\x0fdurationSeconds\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\"5\n" +
	"\x11JA4HLookupRequest\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\"\x85\x02\n" +
	"\x12JA4HLookupResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12 \n" +
	"\vapplication\x18\x02 \x01(\tR\vapplication\x12\x18\n" +
	"\alibrary\x18\x03 \x01(\tR\alibrary\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\x12\x1a\n" +
	"\bverified\x18\x05 \x01(\bR\bverified\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12!\n" +
	"\fthreat_score\x18\a \x01(\x01R\vthreatScore\x12*\n" +
	"\x11is_wildcard_match\x18\b \x01(\bR\x0fisWildcardMatch\"E\n" +
	"\x11JA4TLookupRequest\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"\x96\x01\n" +
	"\x12JA4TLookupResponse\x12\x1e\n" +
	"\n" +
	"suspicious\x18\x01 \x01(\bR\n" +
	"suspicious\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x01R\triskScore\x12)\n" +
	"\x10matched_patterns\x18\x04 \x03(\tR\x0fmatchedPatterns\"d\n" +
	"\x10BotVerifyRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12!\n" +
	"\fforce_lookup\x18\x03 \x01(\bR\vforceLookup\"\x8c\x02\n" +
	"\x11BotVerifyResponse\x12\x1f\n" +
	"\vis_verified\x18\x01 \x01(\bR\n" +
	"isVerified\x12\x19\n" +
	"\bbot_type\x18\x02 \x01(\tR\abotType\x12\x1f\n" +
	"\vreverse_dns\x18\x03 \x01(\tR\n" +
	"reverseDns\x12\x1f\n" +
	"\vforward_dns\x18\x04 \x01(\tR\n" +
	"forwardDns\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12)\n" +
	"\x10is_impersonation\x18\x06 \x01(\bR\x0fisImpersonation\x128\n" +
	"\bcategory\x18\a \x01(\x0e2\x1c.packetyeeter.v1.BotCategoryR\bcategory\"G\n" +
	"\x16AICrawlerVerifyRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\"\x88\x01\n" +
	"\x17AICrawlerVerifyResponse\x12\x1f\n" +
	"\vis_verified\x18\x01 \x01(\bR\n" +
	"isVerified\x12!\n" +
	"\fcrawler_type\x18\x02 \x01(\tR\vcrawlerType\x12)\n" +
	"\x10is_impersonation\x18\x03 \x01(\bR\x0fisImpersonation\"<\n" +
	"\x12ThreatIntelRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x16\n" +
	"\x06enrich\x18\x02 \x01(\bR\x06enrich\"\xa9\x02\n" +
	"\x13ThreatIntelResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12!\n" +
	"\fthreat_score\x18\x02 \x01(\x01R\vthreatScore\x12(\n" +
	"\x10is_known_scanner\x18\x03 \x01(\bR\x0eisKnownScanner\x12\x15\n" +
	"\x06is_tor\x18\x04 \x01(\bR\x05isTor\x12\x15\n" +
	"\x06is_vpn\x18\x05 \x01(\bR\x05isVpn\x12\x19\n" +
	"\bis_cloud\x18\x06 \x01(\bR\aisCloud\x12\x19\n" +
	"\bis_proxy\x18\a \x01(\bR\aisProxy\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x18\n" +
	"\asources\x18\t \x03(\tR\asources\x12\x1d\n" +
	"\n" +
	"open_ports\x18\n" +
	" \x01(\x05R\topenPorts\"9\n" +
	"\x11ReputationRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xae\x01\n" +
	"\x12ReputationResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12\x1a\n" +
	"\boffenses\x18\x02 \x01(\x05R\boffenses\x127\n" +
	"\tlast_seen\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x15\n" +
	"\x06is_bad\x18\x04 \x01(\bR\x05isBad\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xb2\x01\n" +
	"\vBlockReport\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x03R\x0fdurationSeconds\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x93\x02\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12=\n" +
	"\fuptime_since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vuptimeSince\x12O\n" +
	"\n" +
	"components\x18\x04 \x03(\v2/.packetyeeter.v1.HealthResponse.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xa6\x04\n" +
	"\n" +
	"SignalType\x12\x12\n" +
	"\x0eSIGNAL_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10SIGNAL_SYN_FLOOD\x10\x01\x12\x14\n" +
	"\x10SIGNAL_BAD_FLAGS\x10\x02\x12\x15\n" +
	"\x11SIGNAL_ICMP_FLOOD\x10\x03\x12\x14\n" +
	"\x10SIGNAL_UDP_FLOOD\x10\x04\x12\x16\n" +
	"\x12SIGNAL_TTL_ANOMALY\x10\x05\x12\x19\n" +
	"\x15SIGNAL_WINDOW_ANOMALY\x10\x06\x12\x1e\n" +
	"\x1aSIGNAL_PACKET_SIZE_UNIFORM\x10\a\x12\x19\n" +
	"\x15SIGNAL_TIMING_PATTERN\x10\b\x12\x18\n" +
	"\x14SIGNAL_PORT_SCANNING\x10\t\x12\x1f\n" +
	"\x1bSIGNAL_INCOMPLETE_HANDSHAKE\x10\n" +
	"\x12\x17\n" +
	"\x13SIGNAL_TCP_METADATA\x10\v\x12\x1a\n" +
	"\x16SIGNAL_JA4T_SUSPICIOUS\x10(\x12!\n" +
	"\x1dSIGNAL_HIGH_LATENCY_HANDSHAKE\x10)\x12\x1b\n" +
	"\x17SIGNAL_LATENCY_MISMATCH\x10*\x12\x16\n" +
	"\x12SIGNAL_GEO_ANOMALY\x10+\x12\x1d\n" +
	"\x19SIGNAL_CONNECTION_PATTERN\x10,\x12\x1d\n" +
	"\x19SIGNAL_CLOCK_SKEW_ANOMALY\x102\x12\x1a\n" +
	"\x16SIGNAL_ENTROPY_ANOMALY\x103\x12\x1b\n" +
	"\x17SIGNAL_BASELINE_ANOMALY\x104*v\n" +
	"\fSignalSource\x12\x12\n" +
	"\x0eSOURCE_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vSOURCE_EBPF\x10\x01\x12\x18\n" +
	"\x14SOURCE_FINGERPRINTER\x10\x03\x12\x12\n" +
	"\x0eSOURCE_HAPROXY\x10\x04\x12\x13\n" +
	"\x0fSOURCE_ANALYZER\x10\x05*\xbd\x01\n" +
	"\vCommandType\x12\x13\n" +
	"\x0fCOMMAND_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10COMMAND_BLOCK_IP\x10\x01\x12\x16\n" +
	"\x12COMMAND_UNBLOCK_IP\x10\x02\x12\x16\n" +
	"\x12COMMAND_BLOCK_CIDR\x10\x03\x12\x18\n" +
	"\x14COMMAND_UNBLOCK_CIDR\x10\x04\x12\x18\n" +
	"\x14COMMAND_ALLOWLIST_IP\x10\x05\x12\x1f\n" +
	"\x1bCOMMAND_REMOVE_ALLOWLIST_IP\x10\x06*\xd6\x01\n" +
	"\vBotCategory\x12\x18\n" +
	"\x14BOT_CATEGORY_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aBOT_CATEGORY_SEARCH_ENGINE\x10\x01\x12\x1d\n" +
	"\x19BOT_CATEGORY_SOCIAL_MEDIA\x10\x02\x12\x1b\n" +
	"\x17BOT_CATEGORY_LEGITIMATE\x10\x03\x12\x1b\n" +
	"\x17BOT_CATEGORY_AI_CRAWLER\x10\x04\x12\x18\n" +
	"\x14BOT_CATEGORY_SCRAPER\x10\x05\x12\x1a\n" +
	"\x16BOT_CATEGORY_MALICIOUS\x10\x06*a\n" +
	"\n" +
	"EntityType\x12\x12\n" +
	"\x0eENTITY_UNKNOWN\x10\x00\x12\r\n" +
	"\tENTITY_IP\x10\x01\x12\x0e\n" +
	"\n" +
	"ENTITY_ASN\x10\x02\x12\x0f\n" +
	"\vENTITY_JA4H\x10\x03\x12\x0f\n" +
	"\vENTITY_JA4T\x10\x042\x80\x06\n" +
	"\x0fAnalyzerService\x12F\n" +
	"\rStreamSignals\x12\x17.packetyeeter.v1.Signal\x1a\x18.packetyeeter.v1.Command(\x010\x01\x12U\n" +
	"\n" +
	"LookupJA4H\x12\".packetyeeter.v1.JA4HLookupRequest\x1a#.packetyeeter.v1.JA4HLookupResponse\x12U\n" +
	"\n" +
	"LookupJA4T\x12\".packetyeeter.v1.JA4TLookupRequest\x1a#.packetyeeter.v1.JA4TLookupResponse\x12R\n" +
	"\tVerifyBot\x12!.packetyeeter.v1.BotVerifyRequest\x1a\".packetyeeter.v1.BotVerifyResponse\x12d\n" +
	"\x0fVerifyAICrawler\x12'.packetyeeter.v1.AICrawlerVerifyRequest\x1a(.packetyeeter.v1.AICrawlerVerifyResponse\x12[\n" +
	"\x0eGetThreatIntel\x12#.packetyeeter.v1.ThreatIntelRequest\x1a$.packetyeeter.v1.ThreatIntelResponse\x12X\n" +
	"\rGetReputation\x12\".packetyeeter.v1.ReputationRequest\x1a#.packetyeeter.v1.ReputationResponse\x12C\n" +
	"\vReportBlock\x12\x1c.packetyeeter.v1.BlockReport\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x1f.packetyeeter.v1.HealthResponseB!Z\x1fPacketYeeter/api/proto/v1;apiv1b\x06proto3"

var (
	file_v1_packetyeeter_proto_rawDescOnce sync.Once
	file_v1_packetyeeter_proto_rawDescData []byte
)

func file_v1_packetyeeter_proto_rawDescGZIP() []byte {
	file_v1_packetyeeter_proto_rawDescOnce.Do(func() {
		file_v1_packetyeeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_packetyeeter_proto_rawDesc), len(file_v1_packetyeeter_proto_rawDesc)))
	})
	return file_v1_packetyeeter_proto_rawDescData
}

var file_v1_packetyeeter_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_v1_packetyeeter_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_v1_packetyeeter_proto_goTypes = []any{
	(SignalType)(0),                 // 0: packetyeeter.v1.SignalType
	(SignalSource)(0),               // 1: packetyeeter.v1.SignalSource
	(CommandType)(0),                // 2: packetyeeter.v1.CommandType
	(BotCategory)(0),                // 3: packetyeeter.v1.BotCategory
	(EntityType)(0),                 // 4: packetyeeter.v1.EntityType
	(*Signal)(nil),                  // 5: packetyeeter.v1.Signal
	(*TCPContext)(nil),              // 6: packetyeeter.v1.TCPContext
	(*Command)(nil),                 // 7: packetyeeter.v1.Command
	(*JA4HLookupRequest)(nil),       // 8: packetyeeter.v1.JA4HLookupRequest
	(*JA4HLookupResponse)(nil),      // 9: packetyeeter.v1.JA4HLookupResponse
	(*JA4TLookupRequest)(nil),       // 10: packetyeeter.v1.JA4TLookupRequest
	(*JA4TLookupResponse)(nil),      // 11: packetyeeter.v1.JA4TLookupResponse
	(*BotVerifyRequest)(nil),        // 12: packetyeeter.v1.BotVerifyRequest
	(*BotVerifyResponse)(nil),       // 13: packetyeeter.v1.BotVerifyResponse
	(*AICrawlerVerifyRequest)(nil),  // 14: packetyeeter.v1.AICrawlerVerifyRequest
	(*AICrawlerVerifyResponse)(nil), // 15: packetyeeter.v1.AICrawlerVerifyResponse
	(*ThreatIntelRequest)(nil),      // 16: packetyeeter.v1.ThreatIntelRequest
	(*ThreatIntelResponse)(nil),     // 17: packetyeeter.v1.ThreatIntelResponse
	(*ReputationRequest)(nil),       // 18: packetyeeter.v1.ReputationRequest
	(*ReputationResponse)(nil),      // 19: packetyeeter.v1.ReputationResponse
	(*BlockReport)(nil),             // 20: packetyeeter.v1.BlockReport
	(*HealthResponse)(nil),          // 21: packetyeeter.v1.HealthResponse
	nil,                             // 22: packetyeeter.v1.Signal.MetadataEntry
	nil,                             // 23: packetyeeter.v1.HealthResponse.ComponentsEntry
	(*timestamppb.Timestamp)(nil),   // 24: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 25: google.protobuf.Empty
}
var file_v1_packetyeeter_proto_depIdxs = []int32{
	24, // 0: packetyeeter.v1.Signal.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: packetyeeter.v1.Signal.type:type_name -> packetyeeter.v1.SignalType
	1,  // 2: packetyeeter.v1.Signal.source:type_name -> packetyeeter.v1.SignalSource
	22, // 3: packetyeeter.v1.Signal.metadata:type_name -> packetyeeter.v1.Signal.MetadataEntry
	6,  // 4: packetyeeter.v1.Signal.tcp_context:type_name -> packetyeeter.v1.TCPContext
	24, // 5: packetyeeter.v1.Command.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 6: packetyeeter.v1.Command.type:type_name -> packetyeeter.v1.CommandType
	3,  // 7: packetyeeter.v1.BotVerifyResponse.category:type_name -> packetyeeter.v1.BotCategory
	24, // 8: packetyeeter.v1.ReputationResponse.last_seen:type_name -> google.protobuf.Timestamp
	24, // 9: packetyeeter.v1.BlockReport.timestamp:type_name -> google.protobuf.Timestamp
	24, // 10: packetyeeter.v1.HealthResponse.uptime_since:type_name -> google.protobuf.Timestamp
	23, // 11: packetyeeter.v1.HealthResponse.components:type_name -> packetyeeter.v1.HealthResponse.ComponentsEntry
	5,  // 12: packetyeeter.v1.AnalyzerService.StreamSignals:input_type -> packetyeeter.v1.Signal
	8,  // 13: packetyeeter.v1.AnalyzerService.LookupJA4H:input_type -> packetyeeter.v1.JA4HLookupRequest
	10, // 14: packetyeeter.v1.AnalyzerService.LookupJA4T:input_type -> packetyeeter.v1.JA4TLookupRequest
	12, // 15: packetyeeter.v1.AnalyzerService.VerifyBot:input_type -> packetyeeter.v1.BotVerifyRequest
	14, // 16: packetyeeter.v1.AnalyzerService.VerifyAICrawler:input_type -> packetyeeter.v1.AICrawlerVerifyRequest
	16, // 17: packetyeeter.v1.AnalyzerService.GetThreatIntel:input_type -> packetyeeter.v1.ThreatIntelRequest
	18, // 18: packetyeeter.v1.AnalyzerService.GetReputation:input_type -> packetyeeter.v1.ReputationRequest
	20, // 19: packetyeeter.v1.AnalyzerService.ReportBlock:input_type -> packetyeeter.v1.BlockReport
	25, // 20: packetyeeter.v1.AnalyzerService.Health:input_type -> google.protobuf.Empty
	7,  // 21: packetyeeter.v1.AnalyzerService.StreamSignals:output_type -> packetyeeter.v1.Command
	9,  // 22: packetyeeter.v1.AnalyzerService.LookupJA4H:output_type -> packetyeeter.v1.JA4HLookupResponse
	11, // 23: packetyeeter.v1.AnalyzerService.LookupJA4T:output_type -> packetyeeter.v1.JA4TLookupResponse
	13, // 24: packetyeeter.v1.AnalyzerService.VerifyBot:output_type -> packetyeeter.v1.BotVerifyResponse
	15, // 25: packetyeeter.v1.AnalyzerService.VerifyAICrawler:output_type -> packetyeeter.v1.AICrawlerVerifyResponse
	17, // 26: packetyeeter.v1.AnalyzerService.GetThreatIntel:output_type -> packetyeeter.v1.ThreatIntelResponse
	19, // 27: packetyeeter.v1.AnalyzerService.GetReputation:output_type -> packetyeeter.v1.ReputationResponse
	25, // 28: packetyeeter.v1.AnalyzerService.ReportBlock:output_type -> google.protobuf.Empty
	21, // 29: packetyeeter.v1.AnalyzerService.Health:output_type -> packetyeeter.v1.HealthResponse
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_packetyeeter_proto_init() }
func file_v1_packetyeeter_proto_init() {
	if File_v1_packetyeeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_packetyeeter_proto_rawDesc), len(file_v1_packetyeeter_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_packetyeeter_proto_goTypes,
		DependencyIndexes: file_v1_packetyeeter_proto_depIdxs,
		EnumInfos:         file_v1_packetyeeter_proto_enumTypes,
		MessageInfos:      file_v1_packetyeeter_proto_msgTypes,
	}.Build()
	File_v1_packetyeeter_proto = out.File
	file_v1_packetyeeter_proto_goTypes = nil
	file_v1_packetyeeter_proto_depIdxs = nil
}
